.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bbbit_qt test_bbbit_qt
clean: FORCE
	$(MAKE) -C .. bbbit_qt_clean test_bbbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_bbbit_qt_check
bbbit-qt bbbit-qt.exe: FORCE
	 $(MAKE) -C .. bbbit_qt
